# -*- coding: utf-8 -*-

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(600, 601)
        font = QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.bar_monster_health = QProgressBar(Form)
        self.bar_monster_health.setObjectName(u"bar_monster_health")
        self.bar_monster_health.setGeometry(QRect(217, 160, 161, 20))
        self.bar_monster_health.setAutoFillBackground(True)
        self.bar_monster_health.setStyleSheet(u"QProgressBar::chunk {\n"
"     background-color: #FF0000;\n"
" }")
        self.bar_monster_health.setValue(24)
        self.bar_monster_health.setTextVisible(False)
        self.pln_output = QPlainTextEdit(Form)
        self.pln_output.setObjectName(u"pln_output")
        self.pln_output.setGeometry(QRect(13, 190, 571, 271))
        self.pln_output.setFont(font)
        self.btn_quad_1 = QPushButton(Form)
        self.grp_four = QButtonGroup(Form)
        self.grp_four.setObjectName(u"grp_four")
        self.grp_four.addButton(self.btn_quad_1)
        self.btn_quad_1.setObjectName(u"btn_quad_1")
        self.btn_quad_1.setEnabled(True)
        self.btn_quad_1.setGeometry(QRect(10, 520, 131, 41))
        self.btn_quad_2 = QPushButton(Form)
        self.grp_four.addButton(self.btn_quad_2)
        self.btn_quad_2.setObjectName(u"btn_quad_2")
        self.btn_quad_2.setEnabled(True)
        self.btn_quad_2.setGeometry(QRect(155, 520, 131, 41))
        self.btn_quad_3 = QPushButton(Form)
        self.grp_four.addButton(self.btn_quad_3)
        self.btn_quad_3.setObjectName(u"btn_quad_3")
        self.btn_quad_3.setEnabled(True)
        self.btn_quad_3.setGeometry(QRect(300, 520, 131, 41))
        self.btn_quad_4 = QPushButton(Form)
        self.grp_four.addButton(self.btn_quad_4)
        self.btn_quad_4.setObjectName(u"btn_quad_4")
        self.btn_quad_4.setEnabled(True)
        self.btn_quad_4.setGeometry(QRect(450, 520, 131, 41))
        self.btn_triple_1 = QPushButton(Form)
        self.grp_three = QButtonGroup(Form)
        self.grp_three.setObjectName(u"grp_three")
        self.grp_three.addButton(self.btn_triple_1)
        self.btn_triple_1.setObjectName(u"btn_triple_1")
        self.btn_triple_1.setGeometry(QRect(25, 520, 171, 51))
        self.btn_triple_3 = QPushButton(Form)
        self.grp_three.addButton(self.btn_triple_3)
        self.btn_triple_3.setObjectName(u"btn_triple_3")
        self.btn_triple_3.setGeometry(QRect(205, 520, 171, 51))
        self.btn_triple_2 = QPushButton(Form)
        self.grp_three.addButton(self.btn_triple_2)
        self.btn_triple_2.setObjectName(u"btn_triple_2")
        self.btn_triple_2.setGeometry(QRect(390, 520, 171, 51))
        self.btn_double_1 = QPushButton(Form)
        self.grp_two = QButtonGroup(Form)
        self.grp_two.setObjectName(u"grp_two")
        self.grp_two.addButton(self.btn_double_1)
        self.btn_double_1.setObjectName(u"btn_double_1")
        self.btn_double_1.setGeometry(QRect(10, 520, 276, 61))
        self.btn_double_2 = QPushButton(Form)
        self.grp_two.addButton(self.btn_double_2)
        self.btn_double_2.setObjectName(u"btn_double_2")
        self.btn_double_2.setGeometry(QRect(310, 520, 276, 61))
        self.lbl_image = QLabel(Form)
        self.lbl_image.setObjectName(u"lbl_image")
        self.lbl_image.setGeometry(QRect(230, 30, 131, 121))
        self.lbl_image.setAlignment(Qt.AlignCenter)
        self.lbl_health = QLabel(Form)
        self.lbl_health.setObjectName(u"lbl_health")
        self.lbl_health.setGeometry(QRect(20, 480, 221, 31))
        self.lbl_money = QLabel(Form)
        self.lbl_money.setObjectName(u"lbl_money")
        self.lbl_money.setGeometry(QRect(230, 480, 291, 31))
        self.lbl_monster_health = QLabel(Form)
        self.lbl_monster_health.setObjectName(u"lbl_monster_health")
        self.lbl_monster_health.setGeometry(QRect(380, 160, 141, 16))
        self.lbl_monster_name = QLabel(Form)
        self.lbl_monster_name.setObjectName(u"lbl_monster_name")
        self.lbl_monster_name.setGeometry(QRect(100, 0, 391, 20))
        self.lbl_monster_name.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"DnDnD", None))
        self.btn_quad_1.setText(QCoreApplication.translate("Form", u"QUAD 1", None))
        self.btn_quad_2.setText(QCoreApplication.translate("Form", u"QUAD 2", None))
        self.btn_quad_3.setText(QCoreApplication.translate("Form", u"QUAD 3", None))
        self.btn_quad_4.setText(QCoreApplication.translate("Form", u"QUAD 4", None))
        self.btn_triple_1.setText(QCoreApplication.translate("Form", u"TRIPLE 1", None))
        self.btn_triple_3.setText(QCoreApplication.translate("Form", u"TRIPLE 3", None))
        self.btn_triple_2.setText(QCoreApplication.translate("Form", u"TIPLE 2", None))
        self.btn_double_1.setText(QCoreApplication.translate("Form", u"DOUBLE 1", None))
        self.btn_double_2.setText(QCoreApplication.translate("Form", u"DOUBLE 2", None))
        self.lbl_image.setText("")
        self.lbl_health.setText(QCoreApplication.translate("Form", u"\u0412\u0430\u0448\u0435 \u0437\u0434\u043e\u0440\u043e\u0432\u044c\u0435: 100/100", None))
        self.lbl_money.setText(QCoreApplication.translate("Form", u"\u0412\u0430\u0448\u0438 \u043c\u043e\u043d\u0435\u0442\u044b: 20", None))
        self.lbl_monster_health.setText("")
        self.lbl_monster_name.setText("")
    # retranslateUi

